'use client';

export default function TermsOfService() {
  const lastUpdated = "March 13, 2026";

  return (
    <div className="container mx-auto px-4 max-w-4xl py-12 text-slate-300">
      <h1 className="text-4xl font-black mb-4 text-white tracking-tight">Terms of Service</h1>
      <p className="mb-10 text-slate-500 font-medium">Last updated: {lastUpdated}</p>

      <div className="space-y-10 text-sm md:text-base leading-relaxed">
        {/* 1. Acceptance of Terms */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using K-Enter24 ("the Site"), you agree to be bound by these Terms of Service and all applicable laws and regulations. 
            If you do not agree with any of these terms, you are prohibited from using or accessing this site. 
            The materials contained in this website are protected by applicable copyright and trademark law.
          </p>
        </section>

        {/* 2. Eligibility */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">2. Eligibility</h2>
          <p>
            You must be at least 13 years of age to use this Site. By using the Site, you represent and warrant that you meet this age requirement. 
            If you are under 18, you represent that you have your parent or guardian’s permission to use the Site.
          </p>
        </section>

        {/* 3. Description of Service & AI Disclaimer */}
        <section className="p-8 bg-slate-900 rounded-[32px] border border-slate-800">
          <h2 className="text-xl font-bold mb-3 text-white">3. AI-Generated Content & Service Description</h2>
          <p className="mb-4">
            K-Enter24 is an automated news aggregation platform that utilizes Artificial Intelligence (AI) to summarize and translate public news trends. 
            You acknowledge and agree that:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-slate-400">
            <li>Content is generated by AI algorithms and may occasionally contain inaccuracies, biases, or outdated information.</li>
            <li>We do not manually verify every piece of information provided on the Site.</li>
            <li>The Site is for informational and entertainment purposes only and should not be used as a sole basis for making major decisions.</li>
          </ul>
        </section>

        {/* 4. Intellectual Property Rights */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">4. Intellectual Property</h2>
          <div className="space-y-4">
            <p><strong>Our Content:</strong> The design, layout, logos, and custom software code of K-Enter24 are the exclusive property of K-Enter24 and are protected by international copyright laws.</p>
            <p><strong>Aggregated Content:</strong> News headlines, original images, and external snippets are the property of their respective copyright owners. We aggregate this content under "Fair Use" principles for reporting and transformative summary purposes.</p>
          </div>
        </section>

        {/* 5. Copyright Infringement (DMCA) */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">5. Copyright Policy (DMCA)</h2>
          <p>
            We respect the intellectual property rights of others. If you believe that any content on our Site infringes upon your copyright, please notify us immediately at <span className="text-cyan-400">admin@k-enter24.com</span>. 
            Upon receiving a valid request, we will act promptly to remove the infringing material.
          </p>
        </section>

        {/* 6. Affiliate & Advertising Disclosure */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">6. Affiliate & Third-Party Links</h2>
          <p>
            The Site contains links to third-party websites and affiliate programs (including but not limited to Shopee, Amazon, and Involve Asia). 
            We may earn a commission when you click on or make purchases via these links. 
            We are not responsible for the content, privacy policies, or practices of any third-party websites.
          </p>
        </section>

        {/* 7. User Conduct */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">7. User Conduct</h2>
          <p className="mb-4">You agree not to use the Site to:</p>
          <ul className="list-disc pl-6 space-y-2 text-slate-400">
            <li>Attempt to scrape, crawl, or extract data using automated tools without our permission.</li>
            <li>Interfere with the security-related features of the Site.</li>
            <li>Submit fraudulent votes, likes, or feedback.</li>
            <li>Post or transmit any unauthorized advertising or promotional materials.</li>
          </ul>
        </section>

        {/* 8. Limitation of Liability */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">8. Limitation of Liability</h2>
          <p>
            In no event shall K-Enter24 or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) 
            arising out of the use or inability to use the materials on the Site, even if K-Enter24 has been notified orally or in writing of the possibility of such damage.
          </p>
        </section>

        {/* 9. Governing Law */}
        <section>
          <h2 className="text-2xl font-bold mb-4 text-white">9. Governing Law</h2>
          <p>
            These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction where the Site operator is located, 
            and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
          </p>
        </section>

        {/* 10. Contact Us */}
        <section className="p-8 bg-slate-900 rounded-[32px] border border-slate-800">
          <h2 className="text-xl font-bold mb-3 text-white">10. Contact Us</h2>
          <p className="mb-4 text-slate-400">If you have any questions about these Terms, please contact us at:</p>
          <div className="text-cyan-400 font-bold">
            <p>Email: admin@k-enter24.com</p>
          </div>
        </section>
      </div>
    </div>
  );
}
